// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_abcoxp_TMBExports
#include <TMB.hpp>
#include "fixed_frailty.hpp"
#include "fixed_smooth_frailty.hpp"
#include "fixed_smooth.hpp"
#include "fixed.hpp"
#include "GammaNLL.hpp"
#include "NormalNLL.hpp"
#include "smooth.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "fixed_frailty") {
    return fixed_frailty(this);
  } else if(model == "fixed_smooth_frailty") {
    return fixed_smooth_frailty(this);
  } else if(model == "fixed_smooth") {
    return fixed_smooth(this);
  } else if(model == "fixed") {
    return fixed(this);
  } else if(model == "GammaNLL") {
    return GammaNLL(this);
  } else if(model == "NormalNLL") {
    return NormalNLL(this);
  } else if(model == "smooth") {
    return smooth(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
